graphs/graphs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

graphs/main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('', views.mainpage,name='mainpage'),
    path('segmentation', views.segmentation,name='segmentation'),
    path('interactive_segmentation', views.interactive_segmentation,name='interactive_segmentation'),
    path('dropping', views.dropping,name='dropping'),
]

graphs/main/models.py
from django.db import models


class Image(models.Model):
    class Meta:
        db_table = 'image'

    image = models.ImageField(upload_to='images')
    image_verify = models.ImageField(upload_to='imagesverify')


class Result(models.Model):
    class Meta:
        db_table = 'result'

    image_result = models.ImageField(upload_to='imagesresult')

class Graph_and_pixels(models.Model):
    id_graph = models.AutoField(primary_key=True)
    graph = models.TextField()
    object_pixels = models.TextField()
    background_pixels = models.TextField()
    K = models.FloatField()
    tfm = models.FloatField()
    tsm = models.FloatField()

graphs/main/forms.py
from django import forms
from .models import Image


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('image','image_verify')

graphs/main/views.py
import json
import os.path
import re

from django.shortcuts import render

from .algorithm_interface import start_algorithm, start_improving
from .forms import ImageForm
from .models import Graph_and_pixels


def serialize(obj):
    return json.dumps(str(obj)).replace('"', '')


def convert_str_to_list(string):
    list_of_pairs = []
    list_of_coords = list(string[:-1].split(","))
    for i in range(0, len(list_of_coords) - 1, 2):
        list_of_pairs.append((int(list_of_coords[i]), int(list_of_coords[i + 1])))
    # print(list_of_pairs)
    # print(list(set(list_of_pairs)))
    return list(set(list_of_pairs))


def list_to_str(pixels):
    pixels_in_db = ""
    for el in pixels:
        pixels_in_db += f'{el[0]}' + ' ' + f'{el[1]}' + ' '
    return pixels_in_db[:-1]


def graph_string_to_tuple(graph):
    graph_value = graph.split(" ")
    tuple_graph = ((int(graph_value[0]), int(graph_value[1])),)
    del graph_value[0]
    del graph_value[0]
    dict_graph = {}
    for i in range(0, len(graph_value), 3):
        dict_graph.update({(int(graph_value[i]), int(graph_value[i + 1])): float(graph_value[i + 2])})
    tuple_graph += (dict_graph,)
    return tuple_graph


def save_to_database(request, graph, object_pixels, background_pixels, k, tfm, tsm):
    graph_and_pixels = Graph_and_pixels.objects.create(graph=graph, object_pixels=object_pixels,
                                                       background_pixels=background_pixels, K=k, tfm=tfm, tsm=tsm)
    graph_and_pixels.save()
    request.session['id_graph'] = graph_and_pixels.id_graph


def delete_gaps(pixels):
    pixels = pixels.strip()
    pixels = re.sub(" +", " ", pixels)
    return pixels


def mainpage(request, data=None):
    # print(data)
    if data is None:
        data = dict()
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            request.session['image'] = serialize(form.instance.image)
            request.session['image_verify'] = serialize(form.instance.image_verify)
            Graph_and_pixels.objects.all().delete()
    else:
        form = ImageForm()
    try:
        img_session = request.session['image']
        is_download_img = os.path.exists('media/' + img_session)
    except KeyError:
        is_download_img = False
        img_session = None
    data.update({
        'img': img_session,
        'is_download_img': is_download_img,
        'form': form,
    })
    return render(request, 'main/mainpage.html', context=data)


def segmentation(request):
    data = {}
    # img_out = Image.fromarray(data)
    try:
        img_url = 'media/' + request.session['image']
        img_verify_url = 'media/' + request.session['image_verify']
    except KeyError:
        return mainpage(request)
    if request.method == 'POST':
        Graph_and_pixels.objects.all().delete()
        object_pixels = convert_str_to_list(request.POST.get('object_pixels', ''))
        background_pixels = convert_str_to_list(request.POST.get('background_pixels', ''))
        if request.POST.get('is_eight_neighbors', True) == 'on':
            is_four_neighbors = False
        else:
            is_four_neighbors = True
        graph, k, result_img, tfm, tsm = start_algorithm(img_url, img_verify_url, object_pixels, background_pixels,
                                                         is_four_neighbors=is_four_neighbors,
                                                         lyambda=float(
                                                             request.POST.get('lyambda', '1') if request.POST.get(
                                                                 'lyambda', '') != '' else '1'),
                                                         sigma=float(
                                                             request.POST.get('sigma', '0.1') if request.POST.get(
                                                                 'sigma', '') != '' else '0.1'))
        object_pixels = list_to_str(object_pixels)
        background_pixels = list_to_str(background_pixels)
        save_to_database(request, graph, object_pixels, background_pixels, k, tfm, tsm)
        result_url = "media/imagesresult/imgresult.jpeg"
        result_img.save(result_url)
        data.update({
            'result_img': result_url,
            'object_pixels': object_pixels,
            'background_pixels': background_pixels,
            'after_first_launch': True,
            'can_be_interactive_segmentation': True,
        })
        return mainpage(request, data)

    return mainpage(request)


def interactive_segmentation(request):
    data = {}
    try:
        img_url = 'media/' + request.session['image']
        img_verify_url = 'media/' + request.session['image_verify']
        id_graph = request.session['id_graph']
    except KeyError:
        return mainpage(request)
    if request.method == 'POST':
        object_pixels = convert_str_to_list(request.POST.get('new_object_pixels', ''))
        background_pixels = convert_str_to_list(request.POST.get('new_background_pixels', ''))
        # graph = graph_string_to_tuple(Graph_and_pixels.objects.filter(id_graph=id_graph).values('graph')[0].get(
        # 'graph'))
        graph = Graph_and_pixels.objects.filter(id_graph=id_graph).values('graph')[0].get('graph')
        k = Graph_and_pixels.objects.filter(id_graph=id_graph).values('K')[0].get('K')

        graph, result_img, tfm, tsm = start_improving(img_url, img_verify_url, graph, object_pixels,
                                                      background_pixels, k)
        # graph = '3 2 1 2 4 2 3 5'

        object_pixels = list_to_str(object_pixels)
        background_pixels = list_to_str(background_pixels)
        # save_to_database(request, graph,object_pixels, background_pixels, k, tfm=0, tsm=0)
        save_to_database(request, graph, object_pixels, background_pixels, k, tfm, tsm)

        id_graph = request.session['id_graph']
        object_pixels, background_pixels = '', ''
        stop = True
        while stop:
            try:
                object_pixels += ' ' + Graph_and_pixels.objects.filter(id_graph=id_graph).values('object_pixels')[
                    0].get('object_pixels')
                background_pixels += ' ' + \
                                     Graph_and_pixels.objects.filter(id_graph=id_graph).values('background_pixels')[
                                         0].get('background_pixels')
                id_graph -= 1
            except:
                stop = False
        object_pixels = delete_gaps(object_pixels)
        background_pixels = delete_gaps(background_pixels)

        result_url = "media/imagesresult/imgresult.jpeg"
        result_img.save(result_url)

        data.update({
            'after_first_launch': True,
            'can_be_interactive_segmentation': True,
            'object_pixels': object_pixels,
            'background_pixels': background_pixels,
            'result_img': result_url,
        })

    return mainpage(request, data)


def dropping(request):
    data = {}
    if request.method == 'POST':
        Graph_and_pixels.objects.all().delete()
    data.update({
        'can_be_interactive_segmentation': False,
    })
    return mainpage(request, data)

graphs/main/templates/main/mainpage.html
{% extends 'main/wrapper.html' %}
{% load static %}
{% block title %} Сегментация {% endblock %} 
{% block content %}

<div class="main"> 
    <div class="download-container"> 
        <form method="post" enctype="multipart/form-data" action="/"> 
            {% csrf_token %}
            <label for="id_image">Изображение:</label> <input type="file"  class="inline" name="image" accept="image/*" required id="id_image">
            <label for="id_image_verify">Изображение для проверки:</label> <input type="file"  class="inline" name="image_verify" accept="image/*" required id="id_image_verify">
            <button type="submit" class ="my-button inline"> Загрузить изображение </button>
        </form> 
    </div>

    <div class="manage-container"> 
        <!-- Если изображение уже загружено -->
        {% if is_download_img %}
        <form action="segmentation" method="post" class="inline">
            {% csrf_token %}
            <input class="hidden"   id="object_pixels" name="object_pixels" value="">
            <input class="hidden"  id="background_pixels" name="background_pixels" value="">
            <input class="input_data" type="number" step="0.01" id="lyambda" name="lyambda" value=""  placeholder="Лямбда">
            <input class="input_data" type="number"  step="0.01" id="sigma" name="sigma" value="" placeholder="Сигма">
            <label class="switch inline">
                <input id ="is_eight_neighbors" name="is_eight_neighbors" class="inline" name="lamda"  type="checkbox" onclick=changespan_is_eight_neighbors()> 
                <span class="slider round"></span>
            </label>
            <span id="type_of_choose_is_neighbors">
                Четыре соседа
            </span>
            
            {% if not after_first_launch %}
            <input type="submit"  onclick=normalization() class ="my-button" value="Запуск алгоритма">
            {% endif %}
        </form>
        <form action="\" method="post" class="inline">
            {% csrf_token %}
            <input type="submit" class ="my-button inline" value ="Сброс" onclick=dropping()>
        </form>
        <label class="switch inline">
            <input id ="type_of_pixels" class="inline" type="checkbox" onclick=changespan_type_of_pixels()> 
            <span class="slider round"></span>
        </label>
        <span id="type_of_choose_pixels">
            Выбор пикселей объекта 
        </span>
       
        {% if can_be_interactive_segmentation %}
        <form action="interactive_segmentation" method="post" class="inline">
            {% csrf_token %}
            <input class="hidden" id="new_object_pixels" name="new_object_pixels" value="">
            <input class="hidden" id="new_background_pixels" name="new_background_pixels" value="">
            <input type="submit" class ="my-button" value="Улучшить сегментацию">
        </form>
        {% endif %}
    </div>
    
    <div class="screen">
            <canvas id=canvas width=600vmax height=600vmax></canvas>
            <canvas id=pixel_canvas width="400" height="400" ></canvas>
            <canvas id=result_canvas></canvas>
    </div>
</div>

<script type="text/javascript">
    
    </script>


    <script>
        let flag = false, currX = 0, currY = 0, dot_flag = false;
        const x = "black", y = 2;
        const canvas = document.getElementById("canvas");
        const context = canvas.getContext("2d");
        const pixel_canvas = document.getElementById("pixel_canvas");
        const pixel_context = pixel_canvas.getContext("2d");
        const image = new Image();
        image.src="/media/{{ img }}";
        image.crossOrigin = 'anonymous';
        let width, height;
        let object_pixels = [], background_pixels = [];
        let is_background;
        const result = document.getElementById("result_canvas");
        const result_context = result.getContext("2d");
        let ratio, hRatio, vRatio;
        const yellow='#fde910';
        const violet='#a000a0';
        const screenWidth = window.screen.width
        const screenHeight = window.screen.height
        
        function changespan_type_of_pixels(){
            if (document.getElementById('type_of_pixels').checked) document.getElementById("type_of_choose_pixels").textContent='Выбор пикселей фона';
            else document.getElementById("type_of_choose_pixels").textContent='Выбор пикселей объекта';
        };
        function changespan_is_eight_neighbors(){
            if (document.getElementById('is_eight_neighbors').checked) document.getElementById("type_of_choose_is_neighbors").textContent='Восемь соседей';
            else document.getElementById("type_of_choose_is_neighbors").textContent='Четыре соседа';
        };

        function init() {
                pixel_canvas.addEventListener("mousemove", function (e) {
                    findxy('move', e)
                }, false);
                pixel_canvas.addEventListener("mousedown", function (e) {
                    findxy('down', e)
                }, false);
                pixel_canvas.addEventListener("mouseup", function (e) {
                    findxy('up', e)
                }, false);
                pixel_canvas.addEventListener("mouseout", function (e) {
                    findxy('out', e)
                }, false);
            }
        function findxy(res, e) {
            if (res === 'down') {
                currX = e.clientX - canvas.offsetLeft;
                currY = e.clientY - canvas.offsetTop;
        
                flag = true;
                dot_flag = true;
                if (dot_flag) {
                    if (is_pixels_correct(currX,currY)){
                        if (document.getElementById('type_of_pixels').checked) {
                            draw(currX,currY,violet,y);
                            post(currX, currY, 'object_pixels', 'background_pixels');
                            post(currX, currY, 'new_object_pixels', 'new_background_pixels');
                        }
                        else {
                            draw(currX,currY,yellow,y);
                            post(currX, currY, 'object_pixels', 'background_pixels');
                            post(currX, currY, 'new_object_pixels', 'new_background_pixels');
                        }
                    }  
                    dot_flag = false;
                }
            }
            if (res === 'up' || res === "out") {
                flag = false;
            }
            if (res === 'move') {
                if (flag) {
                    currX = e.clientX - canvas.offsetLeft;
                    currY = e.clientY - canvas.offsetTop;
                    if (is_pixels_correct(currX,currY)){
                        if (document.getElementById('type_of_pixels').checked){
                            draw(currX,currY,violet,y)
                            post(currX, currY, 'object_pixels', 'background_pixels')
                            post(currX, currY, 'new_object_pixels', 'new_background_pixels')
                        }
                        else{
                            draw(currX,currY,yellow,y);
                            post(currX, currY, 'object_pixels', 'background_pixels')
                            post(currX, currY, 'new_object_pixels', 'new_background_pixels')
                        }
                    }  
                }
            }
        }
        function draw(currX,currY,color,size){
            pixel_context.beginPath();
            pixel_context.fillStyle = color;
            pixel_context.arc(currX,currY, 5, 0, 2 * Math.PI);
            pixel_context.closePath();
            pixel_context.lineWidth = size;
            pixel_context.fill();   
        }
        function post(currX, currY, id_field_object, id_field_background){
            if (document.getElementById('type_of_pixels').checked) document.getElementById(id_field_background).value+=Math.floor(currY/ratio)+','+Math.floor(currX/ratio)+',';
                else document.getElementById(id_field_object).value+=Math.floor(currY/ratio)+','+Math.floor(currX/ratio)+',';
        }
        function is_pixels_correct(currX, currY){
            return !(currX<0 || currX>width-1 || currY>height-1 || currY<0)
        }
    
        // Когда картинка загрузилась, масштабируем её под канвас
        image.onload=function(){
            hRatio = canvas.width  / image.width;
            vRatio =  canvas.height / image.height;
            ratio  = Math.min ( hRatio, vRatio );
            width = image.width*ratio;
            height = image.height*ratio;
            context.clearRect(0,0,canvas.width, canvas.height);
            canvas.width = width;
            canvas.height = height;
            pixel_canvas.width = width;
            pixel_canvas.height = height; 
            context.drawImage(image, 0,0, width, height); 
            const imgData = context.getImageData(0, 0, canvas.width, canvas.height);
            for (let i = 0; i < imgData.data.length; i += 4) {
                let count = imgData.data[i] * 0.2989 + imgData.data[i + 1] * 0.5870 + imgData.data[i + 2] * 0.1140

                imgData.data[i] = count
                imgData.data[i + 1] = count
                imgData.data[i + 2] = count
            }
            context.putImageData(imgData, 0, 0);

            // Окно результата
            if ('{{ result_img }}'=== 'media/imagesresult/imgresult.jpeg'){
                const image_result = new Image();
                image_result.src='{{ result_img }}';
                image_result.onload=function(){    
                    result_context.drawImage(image_result, 0,0, width, height); 
                    result_context.fill();
                }
            }
            result.width = width;
            result.height = height;

            const object_pixels_add = "{{ object_pixels }}";
            const background_pixels_add = "{{ background_pixels }}";
            const object_pixels_save = "{{ object_pixels }}".split(' ');
            const background_pixels_save = "{{ background_pixels }}".split(' ');
            if (object_pixels_add !== "" || background_pixels_add!== "" ){
                for (let i = 0; i < object_pixels_save.length-1 ; i+=2){
                    draw(Math.round(ratio*Number(object_pixels_save[i+1])), Math.round(ratio*Number(object_pixels_save[i])),yellow,y);
                }
                for (let i = 0; i < background_pixels_save.length-1; i+=2){
                    draw(Math.round(ratio*Number(background_pixels_save[i+1])), Math.round(ratio*Number(background_pixels_save[i])),violet,y)
                }
            }
            init()
        } 

        function init() {
        pixel_canvas.addEventListener("mousemove", function (e) {
            findxy('move', e)
        }, false);
        pixel_canvas.addEventListener("mousedown", function (e) {
            findxy('down', e)
        }, false);
        pixel_canvas.addEventListener("mouseup", function (e) {
            findxy('up', e)
        }, false);
        canvpixel_canvasas.addEventListener("mouseout", function (e) {
            findxy('out', e)
        }, false);
    }
    
             
        // При нажатии на холст рисуем кружочки
        // pixel_canvas.onclick=function(e){
        //     alert(e.clientX);


        // }

        function choose_pixel(e,pixels,color){
            let y;
            let x;
            let pushable = true;
            // для совместимости с другими браузерами
            if(e.offsetX===undefined) {
                x = e.pageX-$(canvas).offset().left;
                y = Math.round(e.pageY-$(canvas).offset().top);
            } 
            else {
                x = e.offsetX;
                y = e.offsetY;
            }
            //Если нажал внутрь существующего кружочка, удаляем его
            for (let i = 0; i < pixels.length ; i++){
                if (Math.sqrt(Math.pow(x-pixels[i][0]*ratio, 2)+Math.pow(y-pixels[i][1]*ratio, 2))<=radius){
                    pixel_context.clearRect(0,0,canvas.width, canvas.height);
                    pixels[i] = pixels[pixels.length - 1];
                    pixels.length--;
                    i--;
                    pushable = false;
                }
            }
            if(pushable){
                pixels.push([Math.round(x/ratio),Math.round(y/ratio)]);
                circle(x,y,radius,color);
            }
            else {
                for (let i = 0; i < object_pixels.length ; i++){
                    circle(ratio*object_pixels[i][0],ratio*object_pixels[i][1],radius,red);
                }
                for (let i = 0; i < background_pixels.length ; i++){
                    circle(ratio*background_pixels[i][0],ratio*background_pixels[i][1],radius,green);
                }

            }   
        }
        function dropping(){
            $.ajax({
                url: 'http://127.0.0.1:8000/dropping',
                type: 'POST',
                headers: {
                "X-CSRFTOKEN": "{{ csrf_token }}"
                }
            }).done(function(response){
           console.log(response);});
           pixel_context.clearRect(0,0,canvas.width, canvas.height);
            document.getElementById('object_pixels').value=' ';
            document.getElementById('background_pixels').value=' ';
            object_pixels=[]; 
            background_pixels=[];
        }
        
        
</script>
{% endif %}
{% endblock %}

graphs/main/templates/main/wrapper.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Cache-Control" content="no-cache">
    <title> {% block title %} {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/mainpage.css'%}">
    <script type="text/javascript" src="{% static 'main/js/jquery.min.js'%}"></script>
    <!-- <script type="text/javascript" src="{% static 'main/js/jquery-ui.min.js'%}"></script>
    <script src="https://use.fontawesome.com/3be064cc4c.js"></script>
    <link rel="icon" href="{% static 'main/img/parfume.svg'%}" sizes="16x16 32х32" >
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">  -->
</head>
<body>

    <main>
      <div id="content">
        {% block content %}
        {% endblock %}
      </div>
    </main>
</body>
</html>